sonar.projectKey=szaib-dev_auth-service
sonar.projectName=auth-service
sonar.organization=szaib-dev

sonar.sources=src
sonar.tests=test

sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**,**/*.config.js,**/*.config.ts
sonar.test.inclusions=**/*.test.ts,**/*.spec.ts,**/*.test.js,**/*.spec.js

sonar.qualitygate.wait=true

sonar.javascript.lcov.reportPaths=./coverage/lcov.info