name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test-and-build:
    name: Test and Build
    runs-on: ubuntu-latest
    environment: DB_PASS
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres -d postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      NODE_ENV: dev
      PORT: 5501
      DATABASE_URL: postgresql://postgres:postgres@127.0.0.1:5432/postgres
      REFRESH_TOKEN_SECRET: ${{ secrets.REFRESH_TOKEN_SECRET }}
      PRIVATE_KEY_SECRET: ${{ secrets.PRIVATE_KEY }}
      JWKS_URI: http://localhost:5501/.well-known/jwks.json

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate Prisma client
        run: pnpm prisma generate

      - name: Apply Prisma migrations
        run: pnpm prisma migrate deploy

      - name: Run ESLint
        run: pnpm lint:check

      - name: Run Jest tests
        run: pnpm test

      - name: Create build
        run: pnpm build

      - name: Sonar Cloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}


  build-and-push-docker:
   name: Build and Push on Docker Hub
   needs: test-and-build
   runs-on: ubuntu-latest
   environment: DB_PASS

   env: 
      IMAGE_NAME: szbr1/auth-service
      IMAGE_TAG:  build-${{github.run_number}}
   if: github.ref == 'refs/heads/main' && github.event_name == 'push'
   steps: 
      - name: Checkout repositary
        uses: actions/checkout@v4

      - name: Log into Docker Hub
        uses: docker/login-action@v4
        with: 
           username: ${{secrets.DOCKER_USERNAME}}
           password: ${{secrets.DOCKER_PASS}}

      - name: Build Docker Image 
        run: docker build -t ${{env.IMAGE_NAME}}:${{env.IMAGE_TAG}} --platform linux/amd64 -f  docker/prod/Dockerfile .
      - name: Push Docker Image to Docker Hub
        run: docker push ${{env.IMAGE_NAME}}:${{env.IMAGE_TAG}}
   





